
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox_Form;

	private global::Gtk.HBox hbox_Head;

	private global::Gtk.Button button_Power;

	private global::Gtk.Button button_SendOn;

	private global::Gtk.Button button_SendOff;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox_Form = new global::Gtk.VBox();
		this.vbox_Form.WidthRequest = 800;
		this.vbox_Form.HeightRequest = 400;
		this.vbox_Form.Name = "vbox_Form";
		this.vbox_Form.Spacing = 6;
		// Container child vbox_Form.Gtk.Box+BoxChild
		this.hbox_Head = new global::Gtk.HBox();
		this.hbox_Head.Name = "hbox_Head";
		this.hbox_Head.Spacing = 6;
		// Container child hbox_Head.Gtk.Box+BoxChild
		this.button_Power = new global::Gtk.Button();
		this.button_Power.WidthRequest = 100;
		this.button_Power.HeightRequest = 100;
		this.button_Power.CanFocus = true;
		this.button_Power.Name = "button_Power";
		this.button_Power.UseUnderline = true;
		this.button_Power.Label = global::Mono.Unix.Catalog.GetString("POWER");
		this.hbox_Head.Add(this.button_Power);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox_Head[this.button_Power]));
		w1.Position = 2;
		w1.Expand = false;
		w1.Fill = false;
		this.vbox_Form.Add(this.hbox_Head);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox_Form[this.hbox_Head]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox_Form.Gtk.Box+BoxChild
		this.button_SendOn = new global::Gtk.Button();
		this.button_SendOn.WidthRequest = 400;
		this.button_SendOn.HeightRequest = 100;
		this.button_SendOn.CanFocus = true;
		this.button_SendOn.Name = "button_SendOn";
		this.button_SendOn.UseUnderline = true;
		this.button_SendOn.Label = global::Mono.Unix.Catalog.GetString("ON");
		this.vbox_Form.Add(this.button_SendOn);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox_Form[this.button_SendOn]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox_Form.Gtk.Box+BoxChild
		this.button_SendOff = new global::Gtk.Button();
		this.button_SendOff.WidthRequest = 400;
		this.button_SendOff.HeightRequest = 100;
		this.button_SendOff.CanFocus = true;
		this.button_SendOff.Name = "button_SendOff";
		this.button_SendOff.UseUnderline = true;
		this.button_SendOff.Label = global::Mono.Unix.Catalog.GetString("OFF");
		this.vbox_Form.Add(this.button_SendOff);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox_Form[this.button_SendOff]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.Add(this.vbox_Form);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 800;
		this.DefaultHeight = 400;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
